# Database init, supports mysql too
database: h2

spring:
  sql:
    init:
      schema-locations: classpath*:db/${database}/schema.sql
      data-locations: classpath*:db/${database}/data.sql

  # Web
  thymeleaf:
    mode: HTML

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true

  # Internationalization
  messages:
    basename: messages/messages

  # Maximum time static resources should be cached
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 12h

  # Logging
  logging:
    level:
      org:
        springframework: INFO

  ai:
    azure:
      openai:
        endpoint: ${AZURE_OPENAI_ENDPOINT}
        client-id: ${CLIENT_ID}
        chat:
          options:
            deployment-name: gpt-4
            temperature: 0.8
        embedding:
          options:
            deployment-name: text-embedding-ada-002
    chat:
      client:
        enabled: true

# PetClinic Agent
petclinic:
  agent:
    name: petclinic agent

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
